### ISSUE TITLE
May the bugs continue

### ISSUE THREAD

**Issue by VegaDeftwing** [lamdu/lamdu#95]
I've got nothing for this one, finally up and running, and launching from a terminal. I can type, I can see things... close, but no cigar. I have a black line going across the background (persists though theme changes) and more importantsly while the Type annotations can appear, no evaluation annotations are showing up.  Tried with disable lcd rendering and still have both issues. The suggestion boxes (typing s to get sqrt) still show up, and from what I can tell things are otherwise working. Any ideas?

Using GL version: "3.0 Mesa 18.0.0"
![lamdu](https://user-images.githubusercontent.com/11283620/38961062-6f9e59c6-432c-11e8-8f34-5599b0a258ea.png)

**Comment by yairchu** [comment]
Regarding the evaluation not working - this may be this issue: https://github.com/lamdu/lamdu/issues/90

Can you try to build the latest version and see if the problem persists?

As for graphics glitches - could you run GLFW-b-demo and see if it has the same problems?

**Comment by yairchu** [comment]
So wrt node, re-building the latest version should build a suitable version of node instead and this problem should be solved.

**Comment by yairchu** [comment]
Wrt [GLFW-b-demo](https://github.com/bsl/GLFW-b-demo), if it doesn't build, you could open an issue for it and link it here and I'll try to help.

**Comment by VegaDeftwing** [comment]
Welp, I tried the latest version and no dice. Eval still doesn't show.

**Comment by Peaker** [comment]
@VegaDeftwing

* Graphics: can you try running GLFW-b-demo? If it works, then the problem is in Lamdu.
* Evaluation: Are you building with stack? Can you run the newest version and report console output (stderr)? It should be more informative about nodejs execution failures.

**Comment by yairchu** [comment]
Closing for now. If problem's still there with new versions or can gather the extra info we'll reopen this
